package net.marcoromano.mooviez.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF006D3D)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFF97F7B7)
internal val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
internal val md_theme_light_secondary = Color(0xFF006683)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFBDE9FF)
internal val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
internal val md_theme_light_tertiary = Color(0xFF006494)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFCBE6FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFDFBFF)
internal val md_theme_light_onBackground = Color(0xFF001B3D)
internal val md_theme_light_surface = Color(0xFFFDFBFF)
internal val md_theme_light_onSurface = Color(0xFF001B3D)
internal val md_theme_light_surfaceVariant = Color(0xFFDCE5DB)
internal val md_theme_light_onSurfaceVariant = Color(0xFF414942)
internal val md_theme_light_outline = Color(0xFF717971)
internal val md_theme_light_inverseOnSurface = Color(0xFFECF0FF)
internal val md_theme_light_inverseSurface = Color(0xFF003062)
internal val md_theme_light_inversePrimary = Color(0xFF7BDA9C)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF006D3D)
internal val md_theme_light_outlineVariant = Color(0xFFC0C9BF)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF7BDA9C)
internal val md_theme_dark_onPrimary = Color(0xFF00391D)
internal val md_theme_dark_primaryContainer = Color(0xFF00522D)
internal val md_theme_dark_onPrimaryContainer = Color(0xFF97F7B7)
internal val md_theme_dark_secondary = Color(0xFF65D3FF)
internal val md_theme_dark_onSecondary = Color(0xFF003546)
internal val md_theme_dark_secondaryContainer = Color(0xFF004D64)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFBDE9FF)
internal val md_theme_dark_tertiary = Color(0xFF8ECDFF)
internal val md_theme_dark_onTertiary = Color(0xFF00344F)
internal val md_theme_dark_tertiaryContainer = Color(0xFF004B71)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFCBE6FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF001B3D)
internal val md_theme_dark_onBackground = Color(0xFFD6E3FF)
internal val md_theme_dark_surface = Color(0xFF001B3D)
internal val md_theme_dark_onSurface = Color(0xFFD6E3FF)
internal val md_theme_dark_surfaceVariant = Color(0xFF414942)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9BF)
internal val md_theme_dark_outline = Color(0xFF8B938A)
internal val md_theme_dark_inverseOnSurface = Color(0xFF001B3D)
internal val md_theme_dark_inverseSurface = Color(0xFFD6E3FF)
internal val md_theme_dark_inversePrimary = Color(0xFF006D3D)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF7BDA9C)
internal val md_theme_dark_outlineVariant = Color(0xFF414942)
internal val md_theme_dark_scrim = Color(0xFF000000)

internal val seed = Color(0xFF90CEA2)
