name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit hash'
        required: true
      version:
        description: 'Version name'
        required: true

env:
  COMMIT_HASH: ${{ github.event.inputs.commit }}
  VERSION_NAME: ${{ github.event.inputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Checkout repository at ${{ github.event.inputs.commit }}
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.commit }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Decode secrets
        env:
          STORE_FILE: ${{ secrets.STORE_FILE }}
          PLAYSTORE_FILE: ${{ secrets.PLAYSTORE_FILE }}
        run: |
          mkdir -p app/.secrets
          echo $STORE_FILE | base64 --decode > app/.secrets/keystore.jks
          echo $PLAYSTORE_FILE | base64 --decode > app/.secrets/playstore.json
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        id: gradle
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: true
      - name: Build release bundle and publish it to Play Store
        run: ./gradlew :app:bundleRelease :app:uploadCrashlyticsMappingFileRelease :app:publishReleaseBundle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Create Github release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ env.COMMIT_HASH }}
          tag_name: '${{ env.VERSION_NAME }}'
          generate_release_notes: true
